require 'uri'
require 'open-uri'
require 'nokogiri'
require 'faraday'

bottles = [
  "3 Fonteinen Oude Gueuze Cuvee Armand & Gaston b2 Oude Gueuze",
  "AleSmith Grand Cru Belgian Strong Ale",
  "AleSmith Private Stock Ale English Strong Ale",
  "AleSmith Speedway Stout Imperial Coffee Stout",
  "AleSmith Speedway Stout Imperial Coffee Stout",
  "AleSmith Thai Speedway Stout Imperial Coffee Stout w. coconut  basil etc",
  "AleSmith Pizza Port Logical Choice Triple IPA",
  "Almanac Farmer's Reserve Blackberry Wine BA Sour Ale w. blackberries",
  "Almanac Farmer's Reserve Raspberry Wine BA Sour Ale w. raspberries",
  "Almanac Pumpkin Sour Bourbon BA Sour Ale w. pumpkin & spices",
  "Almanac Vanilla Cherry Dogpatch Wine BA Sour Ale w. cherries & vanilla beans",
  "Almanac White Label Wine BA Sour Ale w. grapes",
  "American Solera Bright Black Delight",
  "American Solera Eng-Yak",
  "American Solera Money Blend b2",
  "Anchorage White Out Witbier",
  "Baladin Lune 2012",
  "Cigar City 110K+OT batch #9",
  "Cigar City Marshal Zhukov Vanilla Hazelnut",
  "Cigar City Raspberry Halo",
  "Dark Horse Plead the 5th",
  "De Struise Tsjeeses Reserva Bourbon BA",
  "Dugges Cocoa Cacao",
  "Dugges Tropic Thunder",
  "Dunham Imperial Black IPA",
  "Evil Twin Even More Coco Jesus",
  "Evil Twin Even More Jesus",
  "Evil Twin Even More Jesus",
  "Evil Twin I Always Felt Closer To IPAs Than I Did To People",
  "Evil Twin Imperial Biscotti Break",
  "Evil Twin Mission Gose",
  "Evil Twin Sauerkirsche Stout",
  "Firestone Walker Pale 31",
  "Firestone Walker Pivo Pils",
  "Firestone Walker Velvet Merlin",
  "Freigeist Room 101",
  "Great Divide Hibernation Ale",
  "Hoppin' Frog BA B.O.R.I.S. the Crusher",
  "Hoppin' Frog BA T.O.R.I.S. the Tyrant",
  "Jackie O's  Oil of Aphrodite",
  "Jackie O's  Dark Apparition",
  "Jackie O's  Bourbon BA Dark Apparition",
  "Le Trou du Diable Dulcis Succubus",
  "Le Trou du Diable Imperatrice Special",
  "Leelanau Evil Twin The Dogmatist",
  "Logsdon  Peche 'n Brett",
  "Maui Brewing Coconut Porter",
  "Modern Times Black House",
  "Omnipollo Noa Pecan Mud Cake Stout",
  "Omnipollo Noa Pecan Mud Cake Stout Bourbon BA",
  "Omnipollo Original Blueberry Slab Cake Ice Cream",
  "Omnipollo Original Maple Truffle Ice Cream Waffle",
  "Omnipollo Original Popsicle Pils",
  "Omnipollo  Original Raspberry Meringue Ice Cream Pie",
  "Omnipollo Crooked Stave Raspberry Bianca Wild Wild Tart",
  "Omnipollo Evil Twin Old Fashioned Lemonade IPA",
  "Oskar Blues Dale's Pale Ale",
  "Oskar Blues Old Chub",
  "Oskar Blues Ten Fidy",
  "Perennial Jack Rose",
  "Perennial 17",
  "Pipeworks Mango Guppy",
  "Pipeworks Lizard King",
  "Pipeworks Ninja vs Unicorn",
  "Pipeworks Cinnamon Abduction",
  "Pipeworks Smoke Break Abduction",
  "Pohjala Pime Oo",
  "Sahtipaja BA Babushka Maria",
  "Sante Adairius  Four Legs Good",
  "SOLE  Over 9000",
  "SOLE Evil Twin Evil Smoosh",
  "Stigbergets Amazing Haze",
  "Stigbergets  West Coast IPA",
  "Stigbergets Mikkeller American Cream",
  "The Bruery Hottenroth",
  "The Bruery Melange #3",
  "The Bruery San Pagaie",
  "The Bruery Saule",
  "The Bruery The Order",
  "The Lost Abbey Angel's Share Bourbon Barrel",
  "The Lost Abbey Cuvee de Tommee",
  "The Lost Abbey Deliverance Ale",
  "The Lost Abbey Ex Cathedra",
  "The Lost Abbey My Black Parade",
  "The Veil Fried Fried Chicken Chicken",
  "Westbrook Imperial Mexican Biscotti Cake Break",
  "Westbrook Key Lime Pie Gose",
  "Westbrook Mexican Cake 2017",
  "Westbrook White Thai",
  "Wicked Weed  Old Fashioned",
  "Wicked Weed  Recurrant",
  "Mikkeller 1000 IBU",
  "Mikkeller 12 oz Winale",
  "Mikkeller Amass Crazy Plum",
  "Mikkeller Arh Hvad!?",
  "Mikkeller Beer Geek Breakfast",
  "Mikkeller Beer Geek Cocoa Shake",
  "Mikkeller Beer Geek Dessert",
  "Mikkeller Beer Geek Limfjordsporter",
  "Mikkeller Beer Geek Vanilla Maple Shake",
  "Mikkeller Beer Hop Breakfast",
  "Mikkeller Beer Traveler BA Oloroso",
  "Mikkeller Big Worster",
  "Mikkeller Black",
  "Mikkeller Cascade IIPA",
  "Mikkeller Chipotle Chili Porter",
  "Mikkeller Citra IIPA",
  "Mikkeller Drinkin Berliner Yuzu",
  "Mikkeller K:rlek 11",
  "Mikkeller Mastodon Mother Puncher",
  "Mikkeller MBCC Spontanyuzu",
  "Mikkeller Monk's Brew",
  "Mikkeller Mosaic IIPA",
  "Mikkeller Nelson Sauvin",
  "Mikkeller Nelson Sauvin BA Champagne",
  "Mikkeller Peter  Pale and Mary",
  "Mikkeller Raspberry Quadrupelbock BA Brandy",
  "Mikkeller Raspberry Trippelbock BA Bourbon",
  "Mikkeller Recipe 1000 BA Sauternes",
  "Mikkeller Simcoe IIPA",
  "Mikkeller Skor BA Red Wine",
  "Mikkeller Spontanblueberry",
  "Mikkeller SpontanCherry",
  "Mikkeller Spontandryhop Centennial",
  "Mikkeller Spontandryhop Citra",
  "Mikkeller Spontandryhop Mosaic",
  "Mikkeller Spontanfigs",
  "Mikkeller Spontanlingonberry",
  "Mikkeller Spontanlychee",
  "Mikkeller Spontannelsonsauvin",
  "Mikkeller Spontanyuzu",
  "Mikkeller William",
  "Mikkeller Winbic",
  "Mikkeller San Diego Ny Verden",
  "Mikkeller Anchorage Invasion",
  "Mikkeller Anchorage AK Alive",
  "Mikkeller Boon Oude Geuze",
  "Mikkeller Boon Oude Geuze Calvados",
  "Mikkeller Lindemans Spontanbasil",
  "Mikkeller Omnipollo Prince & Pauper",
  "Mikkeller Three Floyds Majsgoop",
  "Mikkeller Three Floyds Bla Spogelse"
]
base_url = 'https://untappd.com/search?q='

bottles.each do |name|
  new_name = name
  grade = nil

  while grade == nil && new_name != '' do
    page = Nokogiri::HTML(open("#{base_url}#{URI::escape(new_name)}"))
    grade = page.css('.beer-item .num').first
    new_name = new_name.split[0..-2].join(' ') unless grade
  end

  if grade
    puts "#{new_name}, #{grade.content.gsub(/[\(\)]/, '')}"
  else
    puts "#{name}, n/a"
  end
end
